/* ============================================================
   ДФМ НБТ — interactions + i18n (РУ / ТҶ / EN)
   ============================================================ */

const I18N = {
  ru: {
    "top.npa": "Правовой портал НБТ",
    "top.map": "Карта сайта",
    "top.a11y": "Версия для слабовидящих",
    "brand.dep": "Департамент финансового мониторинга",
    "brand.bank": "при Национальном банке Таджикистана",
    "search.ph": "Поиск по сайту…",
    "cta.cabinet": "Личный кабинет субъекта",
    "nav.about": "О Департаменте",
    "nav.subjects": "Субъектам финмониторинга",
    "nav.legal": "Правовая база",
    "nav.counter": "Противодействие",
    "nav.intl": "Международное сотрудничество",
    "nav.press": "Пресс-центр",
    "nav.services": "Сервисы",
    "sub.about.1": "О Департаменте",
    "sub.about.2": "Задачи и функции",
    "sub.about.3": "Правовой статус и полномочия",
    "sub.about.4": "Структура и руководство",
    "sub.about.5": "История создания",
    "sub.about.6": "Контакты",
    "sub.subjects.1": "Кто является субъектом ПОД/ФТ/ФРОМП",
    "sub.subjects.2": "Постановка на учёт / регистрация",
    "sub.subjects.3": "Порядок направления сообщений",
    "sub.subjects.4": "Личный кабинет / электронная подача",
    "sub.subjects.5": "Требования к внутреннему контролю",
    "sub.subjects.6": "Методические рекомендации и типологии",
    "sub.subjects.7": "Обучение (УМЦ)",
    "sub.subjects.8": "Часто задаваемые вопросы",
    "sub.legal.1": "Законы РТ (ПОД/ФТ/ФРОМП)",
    "sub.legal.2": "Нормативные акты НБТ и ДФМ",
    "sub.legal.3": "40 Рекомендаций ФАТФ",
    "sub.legal.4": "Международные конвенции и стандарты",
    "sub.legal.5": "Проекты нормативных актов",
    "sub.counter.1": "Отмывание доходов (ПОД)",
    "sub.counter.2": "Финансирование терроризма (ФТ)",
    "sub.counter.3": "Финансирование ОМП (ФРОМП)",
    "sub.counter.4": "Перечень террористов / санкционные списки",
    "sub.counter.5": "Национальная оценка рисков (NRA)",
    "sub.counter.6": "Финансовые расследования и типологии",
    "sub.intl.1": "ФАТФ и региональные органы (ЕАГ / APG)",
    "sub.intl.2": "Группа Эгмонт",
    "sub.intl.3": "Двусторонние соглашения",
    "sub.intl.4": "Взаимная оценка (Mutual Evaluation)",
    "sub.press.1": "Новости и события",
    "sub.press.2": "Пресс-релизы",
    "sub.press.3": "Публикации, отчёты, бюллетени",
    "sub.press.4": "Видео и медиа",
    "sub.press.5": "Анонсы обучающих мероприятий",
    "hero.badge": "Подразделение финансовой разведки Республики Таджикистан",
    "hero.title1": "Противодействие незаконным ",
    "hero.titleAccent": "финансовым операциям",
    "hero.title2": " в Республике Таджикистан",
    "hero.sub": "Уполномоченный орган финансовой разведки осуществляет выявление, анализ и пресечение легализации преступных доходов, финансирования терроризма и финансирования распространения оружия массового поражения.",
    "hero.cta1": "Направить сообщение",
    "hero.cta2": "Требования к субъектам",
    "hero.stat1": "1 200+",
    "hero.stat1l": "субъектов финансового мониторинга",
    "hero.stat2": "40",
    "hero.stat2l": "Рекомендации ФАТФ",
    "hero.stat3": "24/7",
    "hero.stat3l": "приём финансовых сообщений",
    "aud.eyebrow": "Целевые разделы",
    "aud.title": "Информация по категориям",
    "aud.c1t": "Субъектам финансового мониторинга",
    "aud.c1p": "Требования к постановке на учёт, порядку представления сведений, организации внутреннего контроля и доступу к электронным сервисам.",
    "aud.c2t": "Гражданам и организациям",
    "aud.c2p": "Порядок направления сообщений о подозрительных операциях, разъяснения законодательства и права граждан в сфере финансового мониторинга.",
    "aud.c3t": "Государственным органам и партнёрам",
    "aud.c3p": "Межведомственное взаимодействие, сотрудничество с зарубежными ПФР и международными организациями в сфере ПОД/ФТ/ФРОМП.",
    "aud.go": "Перейти в раздел",
    "dir.eyebrow": "Функции уполномоченного органа",
    "dir.title": "Ключевые направления деятельности",
    "dir.link": "Все направления",
    "dir.c1a": "ПОД",
    "dir.c1t": "Отмывание доходов (ПОД)",
    "dir.c1p": "Осуществление финансового мониторинга и оперативного анализа операций с целью выявления и пресечения легализации преступных доходов.",
    "dir.c2a": "ФТ",
    "dir.c2t": "Финансирование терроризма (ФТ)",
    "dir.c2p": "Выявление и блокирование финансовых потоков, направленных на поддержку террористической и экстремистской деятельности.",
    "dir.c3a": "ФРОМП",
    "dir.c3t": "Финансирование распространения ОМП",
    "dir.c3p": "Выявление схем финансирования распространения оружия массового поражения и контроль за соблюдением санкционного режима.",
    "dir.more": "Подробнее",
    "reg.title": "Перечни и реестры",
    "reg.p": "Актуальные данные перечня лиц и организаций, связанных с терроризмом и экстремизмом, международных санкционных списков и реестра субъектов финансового мониторинга.",
    "reg.b1": "Перечень террористов и экстремистов",
    "reg.b2": "Реестр субъектов",
    "news.eyebrow": "Пресс-центр",
    "news.title": "Новости и события",
    "news.link": "Все новости",
    "news.t1": "ДФМ при НБТ и АФМ Республики Казахстан подписали Меморандум о взаимодействии в сфере ПОД/ФТ",
    "news.t2": "Внесены изменения в требования к порядку представления сведений субъектами финансового мониторинга",
    "news.t3": "Проведён обучающий семинар для поднадзорных организаций по методологии риск-ориентированного подхода ФАТФ",
    "news.t4": "Утверждён национальный доклад об оценке рисков в сфере легализации преступных доходов и финансирования терроризма",
    "news.tag1": "Межведомственное взаимодействие",
    "news.tag2": "Регулирование",
    "news.tag3": "Методологическое обеспечение",
    "news.tag4": "Аналитика",
    "legal.eyebrow": "Нормативная основа",
    "legal.title": "Правовая база",
    "legal.link": "Полный перечень",
    "legal.i1t": "Закон РТ «О противодействии легализации доходов»",
    "legal.i1s": "№ 684 от 25.03.2011 (в действующей редакции)",
    "legal.i2t": "40 Рекомендаций ФАТФ",
    "legal.i2s": "Международные стандарты ПОД/ФТ/ФРОМП",
    "legal.i3t": "Положение НБТ о внутреннем контроле",
    "legal.i3s": "Требования к субъектам мониторинга",
    "legal.i4t": "Перечень подозрительных операций",
    "legal.i4s": "Критерии и признаки выявления",
    "intl.eyebrow": "Международные партнёры",
    "intl.title": "Международное сотрудничество",
    "intl.fatf": "Международные стандарты ПОД/ФТ",
    "intl.eag": "Евразийская группа",
    "intl.egmont": "Сеть подразделений финразведки",
    "intl.unodc": "Управление ООН по наркотикам",
    "foot.about": "Уполномоченный орган Республики Таджикистан в сфере ПОД/ФТ/ФРОМП.",
    "foot.sections": "Разделы",
    "foot.services": "Сервисы",
    "foot.contacts": "Контакты",
    "foot.s1": "О Департаменте",
    "foot.s2": "Правовая база",
    "foot.s3": "Противодействие",
    "foot.s4": "Пресс-центр",
    "foot.sv1": "Личный кабинет субъекта",
    "foot.sv2": "Подать сообщение",
    "foot.sv3": "Реестр субъектов",
    "foot.sv4": "Электронное обращение",
    "foot.addr": "г. Душанбе, пр. Рудаки 107/А",
    "foot.addrl": "Адрес",
    "foot.email": "info@dmm.tj",
    "foot.hotline": "Телефон доверия",
    "foot.bank": "Национальный банк Таджикистана",
    "foot.copy": "© 2026 Департамент финансового мониторинга при НБТ. Все права защищены.",
    "foot.priv": "Правовая информация",
    "foot.terms": "Условия использования",
    "foot.eobr": "Электронное обращение",
    "drawer.menu": "Меню",
    "about.crumb": "О Департаменте",
    "about.hero.sub": "Уполномоченный орган финансовой разведки Республики Таджикистан",
    "about.nav.title": "Содержание раздела",
    "about.s1.h": "О Департаменте",
    "about.s1.p1": "Департамент финансового мониторинга при Национальном банке Таджикистана (ДФМ при НБТ) является уполномоченным органом Республики Таджикистан в сфере ПОД/ФТ/ФРОМП — противодействия легализации преступных доходов, финансированию терроризма и финансированию распространения оружия массового поражения.",
    "about.s1.p2": "Департамент функционирует как подразделение финансовой разведки (ПФР / Financial Intelligence Unit) в соответствии со стандартами ФАТФ и является членом Группы Эгмонт — международной сети подразделений финансовой разведки.",
    "about.mission.h": "Миссия",
    "about.mission.p": "Защита финансовой системы Республики Таджикистан от незаконных финансовых потоков посредством выявления, анализа и пресечения легализации преступных доходов, финансирования терроризма и финансирования распространения оружия массового поражения.",
    "about.mandate.h": "Мандат",
    "about.mandate.p": "Сбор и анализ финансовых разведывательных данных; надзор за субъектами финансового мониторинга; координация национальной системы ПОД/ФТ/ФРОМП; международное сотрудничество.",
    "about.s2.h": "Задачи и функции",
    "about.f1.t": "Финансовый мониторинг",
    "about.f1.p": "Сбор, обработка и анализ финансовых сообщений, поступающих от субъектов финансового мониторинга.",
    "about.f2.t": "Финансовая разведка",
    "about.f2.p": "Оперативный и стратегический анализ данных в целях выявления схем и типологий незаконных финансовых потоков.",
    "about.f3.t": "Надзор за субъектами",
    "about.f3.p": "Надзор за соблюдением субъектами финансового мониторинга требований законодательства в сфере ПОД/ФТ/ФРОМП.",
    "about.f4.t": "Методологическое обеспечение",
    "about.f4.p": "Разработка нормативных актов, методических рекомендаций и типологий для субъектов мониторинга.",
    "about.f5.t": "Международное сотрудничество",
    "about.f5.p": "Взаимодействие с зарубежными ПФР, ФАТФ, ЕАГ, Группой Эгмонт. Участие во взаимных оценках.",
    "about.f6.t": "Национальная оценка рисков",
    "about.f6.p": "Координация НОР в сфере ПОД/ФТ/ФРОМП и разработка мер по снижению выявленных рисков.",
    "about.s3.h": "Правовой статус и полномочия",
    "about.s3.p": "ДФМ при НБТ осуществляет полномочия уполномоченного органа на основании законодательства Республики Таджикистан и международных договоров.",
    "about.l1.t": "Закон РТ «О ПОД/ФТ»",
    "about.l1.s": "№ 684 от 25.03.2011 (в действующей редакции) — основной закон, устанавливающий правовой статус и полномочия ДФМ",
    "about.l2.t": "Положение о Департаменте",
    "about.l2.s": "Утверждено Советом директоров НБТ — определяет структуру, функции и полномочия ДФМ при НБТ",
    "about.l3.t": "40 Рекомендаций ФАТФ",
    "about.l3.s": "Международные стандарты ПОД/ФТ/ФРОМП, имплементированные в законодательство Республики Таджикистан",
    "about.s4.h": "Структура и руководство",
    "about.s4.p": "ДФМ при НБТ возглавляет руководитель, назначаемый Председателем Национального банка Таджикистана. В структуру входят специализированные отделы финансового мониторинга, надзора и международного сотрудничества.",
    "about.s4.org": "Организационная структура",
    "about.s5.h": "История создания",
    "about.e1.y": "2002",
    "about.e1.t": "Создание ПФР",
    "about.e1.p": "Создание Группы финансовой разведки при Национальном банке Таджикистана — первого подразделения финансовой разведки в стране.",
    "about.e2.y": "2007",
    "about.e2.t": "Членство в Группе Эгмонт",
    "about.e2.p": "Вступление Республики Таджикистан в международную сеть подразделений финансовой разведки — Группу Эгмонт.",
    "about.e3.y": "2011",
    "about.e3.t": "Основной закон ПОД/ФТ",
    "about.e3.p": "Принятие Закона РТ «О противодействии легализации (отмыванию) доходов, полученных преступным путём, и финансированию терроризма».",
    "about.e4.y": "2020",
    "about.e4.t": "Взаимная оценка ЕАГ",
    "about.e4.p": "Прохождение Республикой Таджикистан взаимной оценки Евразийской группы (ЕАГ) по методологии ФАТФ.",
    "about.e5.y": "2024",
    "about.e5.t": "Реорганизация ДФМ",
    "about.e5.p": "Актуализация структуры и мандата в соответствии с современными требованиями ФАТФ и международной практикой ПФР.",
    "about.s6.h": "Контакты",
    "about.s6.addrl": "Юридический адрес",
    "about.s6.addr": "734003, г. Душанбе, пр. Рудаки 107/А, Республика Таджикистан",
    "about.s6.tell": "Телефон",
    "about.s6.tel": "+992 (44) 600-12-12",
    "about.s6.faxl": "Факс",
    "about.s6.fax": "+992 (44) 600-12-13",
    "about.s6.emaill": "Электронная почта",
    "about.s6.hotlinel": "Телефон доверия",
    "about.s6.hoursl": "Режим работы",
    "about.s6.hours": "Пн–Пт: 08:00–17:00",
    "about.s6.break": "Перерыв: 12:00–13:00",
    "about.s6.btn": "Электронное обращение",
    "np.crumb": "Новости и события",
    "np.hero.sub": "Актуальная информация о деятельности Департамента",
    "np.filter.all": "Все публикации",
    "np.filter.coop": "Сотрудничество",
    "np.filter.reg": "Регулирование",
    "np.filter.method": "Методология",
    "np.filter.analytics": "Аналитика",
    "np.filter.training": "Обучение",
    "np.filter.events": "Мероприятия",
    "np.search.ph": "Поиск по новостям…",
    "np.featured.label": "Главная новость",
    "np.read": "Читать далее",
    "np.excerpt.label": "Краткое содержание",
    "np.all.title": "Все публикации",
    "np.pagination.prev": "Назад",
    "np.pagination.next": "Далее",
    "np.count": "публикаций найдено",
    "np.sub.nav.title": "Пресс-центр"
  },
  tg: {
    "top.npa": "Портали ҳуқуқии БМТ",
    "top.map": "Харитаи сомона",
    "top.a11y": "Нусха барои камбинояон",
    "brand.dep": "Раёсати мониторинги молиявӣ",
    "brand.bank": "назди Бонки миллии Тоҷикистон",
    "search.ph": "Ҷустуҷӯ дар сомона…",
    "cta.cabinet": "Кабинети шахсии субъект",
    "nav.about": "Дар бораи Раёсат",
    "nav.subjects": "Ба субъектҳои мониторинг",
    "nav.legal": "Заминаи ҳуқуқӣ",
    "nav.counter": "Муқовимат",
    "nav.intl": "Ҳамкории байналмилалӣ",
    "nav.press": "Маркази матбуот",
    "nav.services": "Хадамот",
    "sub.about.1": "Дар бораи Раёсат",
    "sub.about.2": "Вазифаҳо ва функсияҳо",
    "sub.about.3": "Мақоми ҳуқуқӣ ва ваколатҳо",
    "sub.about.4": "Сохтор ва роҳбарият",
    "sub.about.5": "Таърихи таъсис",
    "sub.about.6": "Тамос",
    "sub.subjects.1": "Кӣ субъекти ПОД/ФТ/ФРОМП аст",
    "sub.subjects.2": "Ба қайд гирифтан / бақайдгирӣ",
    "sub.subjects.3": "Тартиби пешниҳоди хабарҳо",
    "sub.subjects.4": "Кабинети шахсӣ / пешниҳоди электронӣ",
    "sub.subjects.5": "Талаботи назорати дохилӣ",
    "sub.subjects.6": "Тавсияҳои методӣ ва типология",
    "sub.subjects.7": "Таълим (МТМ)",
    "sub.subjects.8": "Саволҳои зуд-зуд пурсидашаванда",
    "sub.legal.1": "Қонунҳои ҶТ (ПОД/ФТ/ФРОМП)",
    "sub.legal.2": "Санадҳои меъёрии БМТ ва РММ",
    "sub.legal.3": "40 Тавсияҳои ФАТФ",
    "sub.legal.4": "Конвенсияҳо ва стандартҳои байналмилалӣ",
    "sub.legal.5": "Лоиҳаҳои санадҳои меъёрӣ",
    "sub.counter.1": "Расмикунонии даромадҳо (ПОД)",
    "sub.counter.2": "Маблағгузории терроризм (ФТ)",
    "sub.counter.3": "Маблағгузории паҳнкунии СҚО (ФРОМП)",
    "sub.counter.4": "Рӯйхати террористон / санксияҳо",
    "sub.counter.5": "Арзёбии миллии хатар (NRA)",
    "sub.counter.6": "Тафтишоти молиявӣ ва типология",
    "sub.intl.1": "ФАТФ ва мақомоти минтақавӣ (ЕАГ / APG)",
    "sub.intl.2": "Гурӯҳи Эгмонт",
    "sub.intl.3": "Созишномаҳои дутарафа",
    "sub.intl.4": "Арзёбии мутақобил (Mutual Evaluation)",
    "sub.press.1": "Хабарҳо ва рӯйдодҳо",
    "sub.press.2": "Хабарҳои матбуотӣ",
    "sub.press.3": "Нашрияҳо, ҳисоботҳо, бюллетенҳо",
    "sub.press.4": "Видео ва медиа",
    "sub.press.5": "Эъломиёт дар бораи чорабиниҳои омӯзишӣ",
    "hero.badge": "Воҳиди иктишофи молиявии Ҷумҳурии Тоҷикистон",
    "hero.title1": "Муқовимат ба амалиётҳои ",
    "hero.titleAccent": "молиявии ғайриқонунӣ",
    "hero.title2": " дар Ҷумҳурии Тоҷикистон",
    "hero.sub": "Мақоми ваколатдори иктишофи молиявӣ ошкорсозӣ, таҳлил ва пешгирии қонунигардонии даромадҳои ҷиноӣ, маблағгузории терроризм ва паҳнкунии силоҳи қатли омро амалӣ мегардонад.",
    "hero.cta1": "Пешниҳоди хабар",
    "hero.cta2": "Талабот ба субъектҳо",
    "hero.stat1": "1 200+",
    "hero.stat1l": "субъекти мониторинги молиявӣ",
    "hero.stat2": "40",
    "hero.stat2l": "Тавсияҳои ФАТФ",
    "hero.stat3": "24/7",
    "hero.stat3l": "қабули хабарҳо",
    "aud.eyebrow": "Бахшҳои мақсадӣ",
    "aud.title": "Маълумот аз рӯи категорияҳо",
    "aud.c1t": "Ба субъектҳои мониторинги молиявӣ",
    "aud.c1p": "Талабот ба бақайдгирӣ, тартиби пешниҳоди маълумот, ташкили назорати дохилӣ ва дастрасӣ ба хадамоти электронӣ.",
    "aud.c2t": "Ба шаҳрвандон ва ташкилотҳо",
    "aud.c2p": "Тартиби пешниҳоди хабар дар бораи амалиёти шубҳанок, шарҳи қонунгузорӣ ва ҳуқуқҳои шаҳрвандон.",
    "aud.c3t": "Ба мақомоти давлатӣ ва шарикон",
    "aud.c3p": "Ҳамкории байнидавлатӣ, ҳамкорӣ бо ВИМ-ҳои хориҷӣ ва ташкилотҳои байналмилалӣ дар соҳаи МД/МТ/МПСҚО.",
    "aud.go": "Ба бахш гузаштан",
    "dir.eyebrow": "Вазифаҳои мақоми ваколатдор",
    "dir.title": "Самтҳои асосии фаъолият",
    "dir.link": "Ҳамаи самтҳо",
    "dir.c1a": "МҚД",
    "dir.c1t": "Қонунигардонии даромадҳо (МД)",
    "dir.c1p": "Амалӣ кардани мониторинги молиявӣ ва таҳлили амалиётҳо бо мақсади ошкор ва пешгирии қонунигардонии даромадҳои ҷиноӣ.",
    "dir.c2a": "МТ",
    "dir.c2t": "Маблағгузории терроризм (МТ)",
    "dir.c2p": "Ошкор ва бастани ҷараёнҳои молиявии равонашуда ба дастгирии фаъолияти террористӣ ва ифротгароӣ.",
    "dir.c3a": "МПСҚ",
    "dir.c3t": "Маблағгузории паҳнкунии СҚО",
    "dir.c3p": "Ошкори схемаҳои маблағгузории паҳнкунии силоҳи қатли ом ва назорат бар риояи режими таҳримотӣ.",
    "dir.more": "Муфассал",
    "reg.title": "Феҳристҳо ва реестрҳо",
    "reg.p": "Дастрасии мустақим ба феҳристи ташкилот ва шахсони ба терроризм алоқаманд, рӯйхатҳои таҳримотӣ ва реестри субъектҳо.",
    "reg.b1": "Феҳристи террористон ва ифротгароён",
    "reg.b2": "Реестри субъектҳо",
    "news.eyebrow": "Маркази матбуот",
    "news.title": "Хабарҳо ва рӯйдодҳо",
    "news.link": "Ҳамаи хабарҳо",
    "news.t1": "РММ ва АММ-и Қазоқистон ёддошти мубодилаи маълумотро имзо карданд",
    "news.t2": "Талабот ба ҳисоботи субъектҳо аз 1 июли соли 2026 нав карда шуд",
    "news.t3": "Семинар барои бонкҳо оид ба муносибати хавфмеҳвари ФАТФ",
    "news.t4": "Ҳисоботи миллии арзёбии хавфҳои МД/МТ нашр шуд",
    "news.tag1": "Ҳамкорӣ",
    "news.tag2": "Танзим",
    "news.tag3": "Омӯзиш",
    "news.tag4": "Таҳлил",
    "legal.eyebrow": "Заминаи меъёрӣ",
    "legal.title": "Заминаи ҳуқуқӣ",
    "legal.link": "Феҳристи пурра",
    "legal.i1t": "Қонуни ҶТ «Дар бораи муқовимат ба қонунигардонии даромад»",
    "legal.i1s": "№ 684 аз 25.03.2011 (таҳрири амалкунанда)",
    "legal.i2t": "40 Тавсияи ФАТФ",
    "legal.i2s": "Стандартҳои байналмилалии МД/МТ",
    "legal.i3t": "Низомномаи БМТ оид ба назорати дохилӣ",
    "legal.i3s": "Талабот ба субъектҳои мониторинг",
    "legal.i4t": "Феҳристи амалиёти шубҳанок",
    "legal.i4s": "Меъёрҳо ва аломатҳои ошкоркунӣ",
    "intl.eyebrow": "Шарикони байналмилалӣ",
    "intl.title": "Ҳамкории байналмилалӣ",
    "intl.fatf": "Стандартҳои байналмилалии МД/МТ",
    "intl.eag": "Гурӯҳи Авруосиё",
    "intl.egmont": "Шабакаи воҳидҳои иктишофи молиявӣ",
    "intl.unodc": "Идораи СММ оид ба маводи мухаддир",
    "foot.about": "Мақоми ваколатдори Ҷумҳурии Тоҷикистон дар соҳаи ПОД/ФТ/ФРОМП.",
    "foot.sections": "Бахшҳо",
    "foot.services": "Хадамот",
    "foot.contacts": "Тамосҳо",
    "foot.s1": "Дар бораи Раёсат",
    "foot.s2": "Заминаи ҳуқуқӣ",
    "foot.s3": "Муқовимат",
    "foot.s4": "Маркази матбуот",
    "foot.sv1": "Кабинети шахсии субъект",
    "foot.sv2": "Пешниҳоди хабар",
    "foot.sv3": "Реестри субъектҳо",
    "foot.sv4": "Муроҷиати электронӣ",
    "foot.addr": "ш. Душанбе, хиёбони Рӯдакӣ 107/А",
    "foot.addrl": "Суроға",
    "foot.email": "info@dmm.tj",
    "foot.hotline": "Телефони боварӣ",
    "foot.bank": "Бонки миллии Тоҷикистон",
    "foot.copy": "© 2026 Раёсати мониторинги молиявӣ назди БМТ. Ҳамаи ҳуқуқҳо ҳифз шудаанд.",
    "foot.priv": "Маълумоти ҳуқуқӣ",
    "foot.terms": "Шартҳои истифода",
    "foot.eobr": "Муроҷиати электронӣ",
    "drawer.menu": "Меню",
    "about.crumb": "Дар бораи Раёсат",
    "about.hero.sub": "Мақоми ваколатдори иктишофи молиявии Ҷумҳурии Тоҷикистон",
    "about.nav.title": "Мундариҷаи бахш",
    "about.s1.h": "Дар бораи Раёсат",
    "about.s1.p1": "Раёсати мониторинги молиявӣ назди Бонки миллии Тоҷикистон (РММ назди БМТ) мақоми ваколатдори Ҷумҳурии Тоҷикистон дар соҳаи муқовимат ба қонунигардонии даромадҳои ҷиноӣ, маблағгузории терроризм ва маблағгузории паҳнкунии силоҳи қатли ом (МД/МТ/МПСҚО) мебошад.",
    "about.s1.p2": "РММ назди БМТ тибқи стандартҳои ФАТФ ҳамчун воҳиди иктишофи молиявӣ (ВИМ / Financial Intelligence Unit) фаъолият намуда, узви Гурӯҳи Эгмонт — шабакаи байналмилалии воҳидҳои иктишофи молиявӣ мебошад.",
    "about.mission.h": "Миссия",
    "about.mission.p": "Ҳифзи системаи молиявии Ҷумҳурии Тоҷикистон аз ҷараёнҳои молиявии ғайриқонунӣ тавассути ошкорсозӣ, таҳлил ва пешгирии қонунигардонии даромадҳои ҷиноӣ, маблағгузории терроризм ва маблағгузории паҳнкунии силоҳи қатли ом.",
    "about.mandate.h": "Мандат",
    "about.mandate.p": "Ҷамъоварӣ ва таҳлили маълумоти иктишофи молиявӣ; назорат бар субъектҳои мониторинги молиявӣ; ҳамоҳангсозии системаи миллии МД/МТ/МПСҚО; ҳамкории байналмилалӣ.",
    "about.s2.h": "Вазифаҳо ва функсияҳо",
    "about.f1.t": "Мониторинги молиявӣ",
    "about.f1.p": "Ҷамъоварӣ, коркард ва таҳлили хабарҳои молиявии расидаги аз субъектҳои мониторинги молиявӣ.",
    "about.f2.t": "Иктишофи молиявӣ",
    "about.f2.p": "Таҳлили амалиётӣ ва стратегии маълумот бо мақсади ошкор кардани схемаҳо ва типологияҳои ҷараёнҳои молиявии ғайриқонунӣ.",
    "about.f3.t": "Назорат бар субъектҳо",
    "about.f3.p": "Назорат аз болои иҷрои талаботи қонунгузорӣ аз ҷониби субъектҳои мониторинги молиявӣ дар соҳаи МД/МТ/МПСҚО.",
    "about.f4.t": "Таъминоти методологӣ",
    "about.f4.p": "Таҳияи санадҳои меъёрӣ, тавсияҳои методӣ ва типологияҳо барои субъектҳои мониторинг.",
    "about.f5.t": "Ҳамкории байналмилалӣ",
    "about.f5.p": "Ҳамкорӣ бо ВИМ-ҳои хориҷӣ, ФАТФ, ЕАГ, Гурӯҳи Эгмонт. Иштирок дар арзёбиҳои мутақобил.",
    "about.f6.t": "Арзёбии миллии хатар",
    "about.f6.p": "Ҳамоҳангсозии АМХ дар соҳаи МД/МТ/МПСҚО ва таҳияи тадбирҳо барои паст кардани хатарҳои ошкоршуда.",
    "about.s3.h": "Мақоми ҳуқуқӣ ва ваколатҳо",
    "about.s3.p": "РММ назди БМТ ваколатҳои мақоми ваколатдорро дар асоси қонунгузории Ҷумҳурии Тоҷикистон ва шартномаҳои байналмилалӣ амалӣ мегардонад.",
    "about.l1.t": "Қонуни ҶТ «Дар бораи МД/МТ»",
    "about.l1.s": "№ 684 аз 25.03.2011 (таҳрири амалкунанда) — қонуни асосии муайянкунандаи мақоми ҳуқуқӣ ва ваколатҳои РММ",
    "about.l2.t": "Муқаррарот дар бораи Раёсат",
    "about.l2.s": "Тасдиқнамудаи Шӯрои директорони БМТ — сохтор, функсияҳо ва ваколатҳоро муайян мекунад",
    "about.l3.t": "40 Тавсияи ФАТФ",
    "about.l3.s": "Стандартҳои байналмилалии МД/МТ/МПСҚО, дар қонунгузории ҶТ татбиқшуда",
    "about.s4.h": "Сохтор ва роҳбарият",
    "about.s4.p": "РММ назди БМТ-ро роҳбаре сарварӣ мекунад, ки аз тарафи Раиси Бонки миллии Тоҷикистон таъин карда мешавад. Сохтори раёсат бахшҳои тахассусии мониторинги молиявӣ, назорат ва ҳамкории байналмилалиро дар бар мегирад.",
    "about.s4.org": "Сохтори ташкилӣ",
    "about.s5.h": "Таърихи таъсис",
    "about.e1.y": "2002",
    "about.e1.t": "Таъсиси ВИМ",
    "about.e1.p": "Таъсиси Гурӯҳи иктишофи молиявӣ назди Бонки миллии Тоҷикистон — аввалин воҳиди иктишофи молиявии кишвар.",
    "about.e2.y": "2007",
    "about.e2.t": "Узвият дар Гурӯҳи Эгмонт",
    "about.e2.p": "Ҷумҳурии Тоҷикистон ба шабакаи байналмилалии воҳидҳои иктишофи молиявӣ — Гурӯҳи Эгмонт — пазируфта шуд.",
    "about.e3.y": "2011",
    "about.e3.t": "Қонуни асосии МД/МТ",
    "about.e3.p": "Қабули Қонуни ҶТ «Дар бораи муқовимат ба қонунигардонии (шустани) даромадҳои ҷиноӣ ва маблағгузории терроризм».",
    "about.e4.y": "2020",
    "about.e4.t": "Арзёбии мутақобили ЕАГ",
    "about.e4.p": "Гузаштани Ҷумҳурии Тоҷикистон аз арзёбии мутақобили ЕАГ мувофиқи методологияи ФАТФ.",
    "about.e5.y": "2024",
    "about.e5.t": "Азнавсозии РММ",
    "about.e5.p": "Навсозии сохтор ва мандат мувофиқ ба талаботи муосири ФАТФ ва амалияи байналмилалии ВИМ-ҳо.",
    "about.s6.h": "Тамос",
    "about.s6.addrl": "Суроғаи ҳуқуқӣ",
    "about.s6.addr": "734003, ш. Душанбе, хиёбони Рӯдакӣ 107/А, Ҷумҳурии Тоҷикистон",
    "about.s6.tell": "Телефон",
    "about.s6.tel": "+992 (44) 600-12-12",
    "about.s6.faxl": "Факс",
    "about.s6.fax": "+992 (44) 600-12-13",
    "about.s6.emaill": "Почтаи электронӣ",
    "about.s6.hotlinel": "Хати боварӣ",
    "about.s6.hoursl": "Соатҳои кор",
    "about.s6.hours": "Душ–Ҷум: 08:00–17:00",
    "about.s6.break": "Танаффус: 12:00–13:00",
    "about.s6.btn": "Муроҷиати электронӣ"
  },
  en: {
    "top.npa": "NBT Legal Portal",
    "top.map": "Sitemap",
    "top.a11y": "Accessibility version",
    "brand.dep": "Department of Financial Monitoring",
    "brand.bank": "under the National Bank of Tajikistan",
    "search.ph": "Search the site…",
    "cta.cabinet": "Reporting Entity Account",
    "nav.about": "About",
    "nav.subjects": "For Reporting Entities",
    "nav.legal": "Legal Framework",
    "nav.counter": "Countering",
    "nav.intl": "International Cooperation",
    "nav.press": "Press Center",
    "nav.services": "Services",
    "sub.about.1": "About the Department",
    "sub.about.2": "Tasks and Functions",
    "sub.about.3": "Legal Status and Powers",
    "sub.about.4": "Structure and Leadership",
    "sub.about.5": "History",
    "sub.about.6": "Contacts",
    "sub.subjects.1": "Who is a Reporting Entity",
    "sub.subjects.2": "Registration",
    "sub.subjects.3": "Reporting Procedures",
    "sub.subjects.4": "Personal Account / E-Filing",
    "sub.subjects.5": "Internal Control Requirements",
    "sub.subjects.6": "Methodological Guidelines",
    "sub.subjects.7": "Training (Training Center)",
    "sub.subjects.8": "FAQ",
    "sub.legal.1": "Laws of Tajikistan (AML/CFT/WMD)",
    "sub.legal.2": "NBT and DFM Regulations",
    "sub.legal.3": "FATF 40 Recommendations",
    "sub.legal.4": "International Conventions",
    "sub.legal.5": "Draft Regulations",
    "sub.counter.1": "Money Laundering (AML)",
    "sub.counter.2": "Terrorism Financing (CFT)",
    "sub.counter.3": "WMD Proliferation Financing",
    "sub.counter.4": "Terrorist List / Sanctions",
    "sub.counter.5": "National Risk Assessment (NRA)",
    "sub.counter.6": "Financial Investigations",
    "sub.intl.1": "FATF and Regional Bodies (EAG / APG)",
    "sub.intl.2": "Egmont Group",
    "sub.intl.3": "Bilateral Agreements",
    "sub.intl.4": "Mutual Evaluation Reports",
    "sub.press.1": "News and Events",
    "sub.press.2": "Press Releases",
    "sub.press.3": "Publications and Reports",
    "sub.press.4": "Video and Media",
    "sub.press.5": "Training Announcements",
    "hero.badge": "Financial Intelligence Unit of the Republic of Tajikistan",
    "hero.title1": "Countering illicit ",
    "hero.titleAccent": "financial flows",
    "hero.title2": " in the Republic of Tajikistan",
    "hero.sub": "The authorized financial intelligence body detects, analyses and disrupts money laundering, terrorism financing and the financing of weapons of mass destruction proliferation.",
    "hero.cta1": "Submit a Report",
    "hero.cta2": "Compliance Requirements",
    "hero.stat1": "1,200+",
    "hero.stat1l": "supervised reporting entities",
    "hero.stat2": "40",
    "hero.stat2l": "FATF Recommendations",
    "hero.stat3": "24/7",
    "hero.stat3l": "report intake",
    "aud.eyebrow": "Information by category",
    "aud.title": "Select your section",
    "aud.c1t": "For Reporting Entities",
    "aud.c1p": "Registration requirements, reporting procedures, internal control obligations and access to electronic services.",
    "aud.c2t": "For Citizens and Organizations",
    "aud.c2p": "Procedures for filing suspicious activity reports, legislative guidance and citizens' rights in financial monitoring.",
    "aud.c3t": "For Government Bodies and Partners",
    "aud.c3p": "Inter-agency cooperation and collaboration with foreign FIUs and international organizations in the field of AML/CFT/CPF.",
    "aud.go": "Go to section",
    "dir.eyebrow": "Mandate and functions",
    "dir.title": "Core areas of activity",
    "dir.link": "All areas",
    "dir.c1a": "AML",
    "dir.c1t": "Money Laundering (AML)",
    "dir.c1p": "Financial monitoring and operational analysis to detect and disrupt the laundering of criminally obtained proceeds within the financial system.",
    "dir.c2a": "CFT",
    "dir.c2t": "Terrorism Financing (CFT)",
    "dir.c2p": "Identifying and blocking financial flows directed at supporting terrorist and extremist activity.",
    "dir.c3a": "CPF",
    "dir.c3t": "WMD Proliferation Financing (CPF)",
    "dir.c3p": "Detecting WMD proliferation financing schemes and monitoring compliance with the applicable sanctions regime.",
    "dir.more": "Learn more",
    "reg.title": "Lists & Registries",
    "reg.p": "Direct access to the list of persons linked to terrorism and extremism, sanctions lists, and the registry of reporting entities.",
    "reg.b1": "Terrorist & Extremist List",
    "reg.b2": "Entity Registry",
    "news.eyebrow": "Press Center",
    "news.title": "News & Events",
    "news.link": "All news",
    "news.t1": "FMD and Kazakhstan's AFA sign a Memorandum of Cooperation in AML/CFT",
    "news.t2": "Amendments adopted to reporting requirements for financial monitoring entities",
    "news.t3": "Training seminar conducted for supervised entities on FATF risk-based approach methodology",
    "news.t4": "National ML/TF risk assessment report approved and published",
    "news.tag1": "Inter-agency Cooperation",
    "news.tag2": "Regulation",
    "news.tag3": "Methodological Support",
    "news.tag4": "Analytics",
    "legal.eyebrow": "Regulatory basis",
    "legal.title": "Legal Framework",
    "legal.link": "Full list",
    "legal.i1t": "RT Law on Countering the Laundering of Proceeds",
    "legal.i1s": "No. 684 of 25.03.2011 (as amended)",
    "legal.i2t": "40 FATF Recommendations",
    "legal.i2s": "International AML/CFT/CPF standards",
    "legal.i3t": "NBT Internal Control Regulation",
    "legal.i3s": "Requirements for reporting entities",
    "legal.i4t": "List of suspicious transactions",
    "legal.i4s": "Criteria and detection indicators",
    "intl.eyebrow": "International partnerships",
    "intl.title": "International Cooperation",
    "intl.fatf": "Global AML/CFT standards",
    "intl.eag": "Eurasian Group",
    "intl.egmont": "Network of financial intelligence units",
    "intl.unodc": "UN Office on Drugs and Crime",
    "foot.about": "The authorized body of the Republic of Tajikistan for AML/CFT/CPF.",
    "foot.sections": "Sections",
    "foot.services": "Services",
    "foot.contacts": "Contacts",
    "foot.s1": "About",
    "foot.s2": "Legal Framework",
    "foot.s3": "Countering",
    "foot.s4": "Press Center",
    "foot.sv1": "Reporting Entity Account",
    "foot.sv2": "Submit a Report",
    "foot.sv3": "Entity Registry",
    "foot.sv4": "Electronic Request",
    "foot.addr": "107/A Rudaki Ave., Dushanbe",
    "foot.addrl": "Address",
    "foot.email": "info@dmm.tj",
    "foot.hotline": "Trust hotline",
    "foot.bank": "National Bank of Tajikistan",
    "foot.copy": "© 2026 Department of Financial Monitoring under the NBT. All rights reserved.",
    "foot.priv": "Legal information",
    "foot.terms": "Terms of use",
    "foot.eobr": "Electronic request",
    "drawer.menu": "Menu",
    "about.crumb": "About the Department",
    "about.hero.sub": "The authorized financial intelligence body of the Republic of Tajikistan",
    "about.nav.title": "Section contents",
    "about.s1.h": "About the Department",
    "about.s1.p1": "The Financial Monitoring Department under the National Bank of Tajikistan (FMD under NBT) is the authorized body of the Republic of Tajikistan responsible for countering money laundering, terrorism financing and the financing of weapons of mass destruction proliferation (AML/CFT/CPF).",
    "about.s1.p2": "FMD under NBT operates as a Financial Intelligence Unit (FIU) in accordance with FATF standards and is a member of the Egmont Group — the international network of financial intelligence units.",
    "about.mission.h": "Mission",
    "about.mission.p": "To protect the financial system of the Republic of Tajikistan from illicit financial flows by detecting, analysing and disrupting money laundering, terrorism financing and financing of WMD proliferation.",
    "about.mandate.h": "Mandate",
    "about.mandate.p": "Collection and analysis of financial intelligence; supervision of reporting entities; coordination of the national AML/CFT/CPF system; international cooperation.",
    "about.s2.h": "Tasks and functions",
    "about.f1.t": "Financial monitoring",
    "about.f1.p": "Collection, processing and analysis of financial disclosures submitted by reporting entities.",
    "about.f2.t": "Financial intelligence",
    "about.f2.p": "Tactical and strategic analysis of data to identify schemes and typologies of illicit financial flows.",
    "about.f3.t": "Supervision of reporting entities",
    "about.f3.p": "Oversight of compliance by reporting entities with AML/CFT/CPF legislation requirements.",
    "about.f4.t": "Methodological support",
    "about.f4.p": "Development of regulations, guidance and typologies for reporting entities.",
    "about.f5.t": "International cooperation",
    "about.f5.p": "Engagement with foreign FIUs, FATF, EAG and Egmont Group. Participation in mutual evaluations.",
    "about.f6.t": "National risk assessment",
    "about.f6.p": "Coordination of the NRA in the AML/CFT/CPF domain and development of risk mitigation measures.",
    "about.s3.h": "Legal status and powers",
    "about.s3.p": "FMD under NBT exercises its powers as the designated authority under Tajik legislation and international treaties.",
    "about.l1.t": "Law of RT on AML/CFT",
    "about.l1.s": "No. 684 of 25.03.2011 (as amended) — the primary law establishing the legal status and powers of the FMD",
    "about.l2.t": "FMD Regulations",
    "about.l2.s": "Approved by the NBT Board of Directors — defines structure, functions and powers of FMD under NBT",
    "about.l3.t": "FATF 40 Recommendations",
    "about.l3.s": "International AML/CFT/CPF standards implemented in Tajikistan's legislation",
    "about.s4.h": "Structure and leadership",
    "about.s4.p": "FMD under NBT is headed by a director appointed by the Chairman of the National Bank of Tajikistan. The department comprises specialized divisions for financial monitoring, supervision and international cooperation.",
    "about.s4.org": "Organizational structure",
    "about.s5.h": "History",
    "about.e1.y": "2002",
    "about.e1.t": "Establishment of the FIU",
    "about.e1.p": "Establishment of the Financial Intelligence Unit under the National Bank of Tajikistan — the country's first dedicated financial intelligence body.",
    "about.e2.y": "2007",
    "about.e2.t": "Egmont Group membership",
    "about.e2.p": "Tajikistan admitted to the international network of financial intelligence units — the Egmont Group.",
    "about.e3.y": "2011",
    "about.e3.t": "Primary AML/CFT law",
    "about.e3.p": "Adoption of the Law of RT 'On Counteracting the Legalisation of Criminal Proceeds and Terrorism Financing'.",
    "about.e4.y": "2020",
    "about.e4.t": "EAG Mutual Evaluation",
    "about.e4.p": "Tajikistan undergoes the EAG Mutual Evaluation in accordance with the FATF methodology.",
    "about.e5.y": "2024",
    "about.e5.t": "FMD reorganisation",
    "about.e5.p": "Structural and mandate update in line with current FATF requirements and international FIU best practices.",
    "about.s6.h": "Contacts",
    "about.s6.addrl": "Legal address",
    "about.s6.addr": "734003, Dushanbe, Rudaki Ave 107/A, Republic of Tajikistan",
    "about.s6.tell": "Phone",
    "about.s6.tel": "+992 (44) 600-12-12",
    "about.s6.faxl": "Fax",
    "about.s6.fax": "+992 (44) 600-12-13",
    "about.s6.emaill": "Email",
    "about.s6.hotlinel": "Hotline",
    "about.s6.hoursl": "Working hours",
    "about.s6.hours": "Mon–Fri: 08:00–17:00",
    "about.s6.break": "Break: 12:00–13:00",
    "about.s6.btn": "Submit an inquiry"
  }
};

const LANG_NAMES = { tg: "ТҶ", ru: "РУ", en: "EN" };
const HTML_LANG = { tg: "tg", ru: "ru", en: "en" };

function applyLang(lang) {
  const dict = I18N[lang] || I18N.ru;
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (dict[key] != null) el.textContent = dict[key];
  });
  document.querySelectorAll("[data-i18n-ph]").forEach(el => {
    const key = el.getAttribute("data-i18n-ph");
    if (dict[key] != null) el.setAttribute("placeholder", dict[key]);
  });
  document.documentElement.setAttribute("lang", HTML_LANG[lang]);
  document.querySelectorAll(".lang button").forEach(b => {
    b.setAttribute("aria-pressed", String(b.dataset.lang === lang));
  });
  try { localStorage.setItem("dmm_lang", lang); } catch (e) {}
}

function initLang() {
  let saved = "ru";
  try { saved = localStorage.getItem("dmm_lang") || "ru"; } catch (e) {}
  applyLang(saved);
  document.querySelectorAll(".lang button").forEach(b => {
    b.addEventListener("click", () => applyLang(b.dataset.lang));
  });
}

function initA11y() {
  const KEY = "dmm_a11y";
  let on = false;
  try { on = localStorage.getItem(KEY) === "1"; } catch (e) {}
  if (on) document.documentElement.classList.add("a11y");
  document.querySelectorAll("[data-a11y-toggle]").forEach(btn => {
    btn.setAttribute("aria-pressed", String(on));
    btn.addEventListener("click", () => {
      on = !document.documentElement.classList.contains("a11y");
      document.documentElement.classList.toggle("a11y", on);
      document.querySelectorAll("[data-a11y-toggle]").forEach(b => b.setAttribute("aria-pressed", String(on)));
      try { localStorage.setItem(KEY, on ? "1" : "0"); } catch (e) {}
    });
  });
}

function initDrawer() {
  const backdrop = document.querySelector(".drawer-backdrop");
  const drawer = document.querySelector(".drawer");
  const openBtn = document.querySelector(".nav-toggle");
  const closeBtn = document.querySelector(".drawer-close");
  if (!drawer) return;
  const open = () => {
    backdrop.classList.add("open");
    drawer.classList.add("open");
    document.body.style.overflow = "hidden";
    closeBtn && closeBtn.focus();
  };
  const close = () => {
    backdrop.classList.remove("open");
    drawer.classList.remove("open");
    document.body.style.overflow = "";
    openBtn && openBtn.focus();
  };
  openBtn && openBtn.addEventListener("click", open);
  closeBtn && closeBtn.addEventListener("click", close);
  backdrop && backdrop.addEventListener("click", close);
  drawer.querySelectorAll("a").forEach(a => a.addEventListener("click", close));
  document.addEventListener("keydown", e => { if (e.key === "Escape") close(); });
}

function initReveal() {
  const els = document.querySelectorAll(".reveal");
  if (!("IntersectionObserver" in window)) {
    els.forEach(el => el.classList.add("in"));
    return;
  }
  const io = new IntersectionObserver((entries) => {
    entries.forEach((e, i) => {
      if (e.isIntersecting) {
        const el = e.target;
        const delay = parseInt(el.dataset.delay || "0", 10);
        setTimeout(() => el.classList.add("in"), delay);
        io.unobserve(el);
      }
    });
  }, { threshold: 0.12, rootMargin: "0px 0px -40px 0px" });
  els.forEach(el => io.observe(el));
}

document.addEventListener("DOMContentLoaded", () => {
  initLang();
  initA11y();
  initDrawer();
  initReveal();
});
